backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "作者", name: "author", widget: "string", default: "杨轩" }
      - { label: "分类", name: "categories", widget: "string" }
      - { label: "标签", name: "tags", widget: "list", allow_add: true }
      - { label: "正文", name: "body", widget: "markdown" }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - label: "设置"
        name: "settings"
        widget: "object"
        fields:
          - { label: "显示目录", name: "showtoc", widget: "boolean", default: true }
          - { label: "显示阅读时间", name: "ShowReadingTime", widget: "boolean", default: true }
          - { label: "显示代码复制按钮", name: "ShowCodeCopyButtons", widget: "boolean", default: true }
